services:
  backend:
    image: harbor.bci-devops.com:8443/cert-monitor/cert-monitor:latest
    container_name: cert-monitor
    ports:
      - "54321:54321"
    environment:
      - PYTHONUNBUFFERED=1
      - SQLALCHEMY_DATABASE_URI=postgresql://certmonitoruser:your_password_here@db:5432/certmonitor
      - UPDATE_INTERVAL=2  # How many minutes between cert/domain expiry checks
      - PYTHONPATH=/cert-monitor
    restart: always
    volumes:
      - .:/cert-monitor
    command: bash -c "gunicorn -w 25 -b 0.0.0.0:54321 cert_monitor:app & python update_data.py"
    depends_on:
      - db
    networks:
      - cmn

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: certmonitoruser
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: certmonitor
    volumes:
      - certmonitor_data:/var/lib/postgresql/data
    networks:
      - cmn

networks:
  cmn:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1460

volumes:
  certmonitor_data: