services:
  backend:
    image: cert-monitor/cert-monitor:latest
    container_name: cert-monitor
    hostname: certificate
    extra_hosts:
      - "certificate.monitor:127.0.0.1"
    ports:
      - "54321:54321"
    env_file:
      - config_vars.env
    restart: always
    volumes:
      - .:/cert-monitor
    command: bash -c "service postfix start && gunicorn -w 25 -b 0.0.0.0:54321 cert_monitor:app & python update_data.py"
    depends_on:
      - db
    networks:
      - cert_monitor_net

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: certmonitoruser
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: certmonitor
    volumes:
      - certmonitor_data:/var/lib/postgresql/data
    networks:
      - cert_monitor_net

networks:
  cert_monitor_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1460

volumes:
  certmonitor_data: