services:
  backend:
    image: cert-monitor/cert-monitor:latest
    container_name: cert-monitor-www
    hostname: certificate
    extra_hosts:
      - "certificate.monitor:127.0.0.1"
    dns:
      - 172.31.11.188
      - 8.8.4.4
    ports:
      - "8001:80"
    env_file:
      - config_vars.env
    restart: always
    volumes:
      - .:/cert-monitor
    command: bash -c "service postfix start && gunicorn -w 5 -b 0.0.0.0:80 cert_monitor:app & python update_data.py"
    depends_on:
      - db
    networks:
      - cert_monitor_net

  db:
    image: postgres:13
    container_name: cert-monitor-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: certmonitoruser
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: certmonitor
    volumes:
      - certmonitor_data:/var/lib/postgresql/data
    networks:
      - cert_monitor_net

networks:
  cert_monitor_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.16/28

volumes:
  certmonitor_data:
